### ISSUE TITLE
[Enhancement] Config to re-enable Fallen Knight Archers

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/ERZ#12]
I saw this in the changelog on the Curse page.
"Fixed Fallen Knights doing zero attack damage; also **now they never spawn with a bow**."
Was something wrong with them?
I don't want to never encounter mounted archers. So a config option to re-enable Fallen Knight Archers would be appreciated.

**Comment by Lothrazar** [comment]
Sure I will look into, i forget why i changed it.

**Comment by Lothrazar** [comment]
I remember now, the ranged attacks werent working .  But still i will revisit this later

**Comment by Lothrazar** [comment]
They now default to 40% archers or something, change in config  https://minecraft.curseforge.com/projects/emberroot-zoo/files/2535187
