### ISSUE TITLE
duplicated id for owl with exotic birds

### ISSUE THREAD

**Issue by 0Navis0** [PrinceOfAmber/ERZ#16]
There is an id conflict for owl with exotic bird which cause crash at startup. https://pastebin.com/wWpVQ32C

**Comment by Lothrazar** [comment]
Yep, its called "owl" but I thought it would be prefixed like this "modid:owl" . no idea how to fix but ill investigate.

**Comment by 0Navis0** [comment]
ExoticBirds dev fixed it on his side. ;)
