### ISSUE TITLE
[1.12.2] Fallen Knights stand in place and fail to attack while flailing wildly

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/ERZ#18]
The fallen knights stop chasing the player, stand in place, and start spazzing out.

**Comment by NotAVerb** [comment]
I encountered a frozen knight doing what appeared to be the same thing.
It looked like he was locked onto a millienaire villager and just stood in place and tracked the villager. the knight was raising and lowering his sword over and over all the while.

**Comment by NotAVerb** [comment]
It also looks like fallen mounts are bucking their mounted knights' off.

**Comment by Lothrazar** [comment]
I assume this was in latest 1.3.5 version?   I redid some AI in latest version to fix some ai problems,,, might have introduced some secondary issues  https://minecraft.curseforge.com/projects/emberroot-zoo/files/2535187

**Comment by NotAVerb** [comment]
I think I've figured it out. Just did another test on 1.3.5. The odd behavior wasn't showing up until I was spawning the knight during the day. Something's happening when they decide to hide under tree cover. The knights can't decide whether to attack or to avoid the sunlight.
They'll also run into and out of water repeatedly.

**Comment by Lothrazar** [comment]
Thanks thats useful information. Must be something with conflicting priorities

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/emberroot-zoo/files/2546169
