### ISSUE TITLE
taiming fairies crashes server

### ISSUE THREAD

**Issue by kreezxil** [PrinceOfAmber/ERZ#19]
Issue:  1.12-1.3.5 crashes dedicated server Forge 1.12.2 build 2619

Notes:
     happens when a player tries to tame a fairy

crash report:
https://gist.github.com/381b9ae53a5352bc01b9c2c0bcced914

fml server latest:
https://gist.github.com/4fbfbe692e1473dae6eeead3d2a6ce92

**Comment by Lothrazar** [comment]
Aha, yep it was trying to play a client only sound on serverside, fix coming soon

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/emberroot-zoo/files/2543368
