### ISSUE TITLE
Unable to spawn mobs in aether_legacy:aether_highlands

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/ERZ#21]
MC 1.12.2
ERZ 1.3.5
My test subjects were the sprite, greater Sprite, and frozen knight. Even after setting `allBiomes` to false, adding `aether_legacy:aether_highlands` to their whitelist, and jacking up spawn weights to 100 for each mob, nothing ever seemed to spawn anywhere in the Aether.

By the way I think the frozen knight should make skeleton noises instead of zombie noises.

**Comment by Lothrazar** [comment]
Ill check into it. 

Note to self   https://minecraft.curseforge.com/projects/aether-legacy/files/2520541

**Comment by Lothrazar** [comment]
Good call on sound too

**Comment by Lothrazar** [comment]
i know this was forever ago. but ive tested this off and on a few times, and yeah i they dont spawn.

But.. This just works fine in other dimensions.  nether,end, mods like hunting dimension.  Dimensions such as the ones in the Sevtech Ages modpack.  

so I think Aether legacy must be doing something specific/special to control the dimension, it has to be fixed on their end.   Sorry.
