### ISSUE TITLE
NPE from Frozen Knight

### ISSUE THREAD

**Issue by NielsPilgaard** [PrinceOfAmber/ERZ#22]
Hey!

Several of my users have experienced crashes when a Mob Grinder from Industrial Foregoing tries to kill a Frozen Knight. 
[Crashlog](https://pastebin.com/yjtFkAf7)

EmberRootZoo-1.12-1.3.5

**Comment by Lothrazar** [comment]
Looks like crash happened because the skeleton was trying to respond-attack and also deal damage by applying slowness potion effect onto, something.

**Comment by NielsPilgaard** [comment]
Is the Frozen Knight hostile towards other mobs?

**Comment by Lothrazar** [comment]
Currently it is not.  There is a config to make it avoid wolves, and a config to make it attack villagers.

If you have suggestions I could add other similar toggles

**Comment by NielsPilgaard** [comment]
The current configs seem good to me, thanks though.

Do you think I could avoid the crash by turning off the Frozen Knight's slowness potion attack?

**Comment by Lothrazar** [comment]
I have a fix for crash in next release.  But until you get it, yeah turning off the slowness potion config might fix it

**Comment by NielsPilgaard** [comment]
Thanks a lot!
