### ISSUE TITLE
Mounted Fallen Knights are frequently bucked off their horses.

### ISSUE THREAD

**Issue by NotAVerb** [PrinceOfAmber/ERZ#23]
Some time after spawning on a zombie horse the knights are dismounted, leaving the pair to wander away from each other.

ERZ 1.3.6

**Comment by Lothrazar** [comment]
I have a fix for this and also https://github.com/PrinceOfAmber/ERZ/issues/18 , but i had to disable the feature where they could use bows. ill have to revisit it later (maybe) if i can find a way to add it without breaking everything else

**Comment by Lothrazar** [comment]
https://minecraft.curseforge.com/projects/emberroot-zoo/files/2546169
