### ISSUE TITLE
Dire Wolf spawning regardless of light levels

### ISSUE THREAD

**Issue by ComaCanadian** [PrinceOfAmber/ERZ#25]
Currently playing sevtech ages 3.0.4. I've placed torches/light sources everywhere and all light levels are covered for normal minecraft spawning (F7, shows no 'x' spots anywhere). Occasionally when I go far enough away from my base, dire wolfs spawn, anywhere (inside ontop, beside). This is not the case of them wandering in, all entries are closed off and there is no spawn-able blocks. 

Is this intended? do they normally spawn in any light level, as long as its stated in the config?

entitydirewolf {
    # They attack as a pack. [default: true]
    B:PackAttack=true

    # Try to spawn in every biome.  If false, it will use the whitelist in this config  [default: true]
    B:allBiomes=true

    # Base attack, before weapons and buffs [range: 0.0 ~ 100.0, default: 1.0]
    S:baseDamage=5

    # Biomes this will spawn into.  Add support for any modded biome here.  Ignored whenever allBiomes is true. https://minecraft.gamepedia.com/Data_values#Biome_IDs [default: ]
    S:biomeWhitelist <
        minecraft:plains
        minecraft:forest
        minecraft:swampland
        minecraft:savanna
        minecraft:mesa
     >

    # Base follow range [range: 0 ~ 32, default: 40]
    I:followRange=40

    # Max health of the mob [range: 1 ~ 100, default: 16]
    I:maxHealth=20

    # Biggest spawn group. [range: 0 ~ 32, default: 1]
    I:maxSpawnCount=1

    # Smallest spawn group. [range: 0 ~ 32, default: 1]
    I:minSpawnCount=1

    # Base speed, before buffs.  (Does not apply to living mobs, you must kill and respawn to see new speed get applied) [range: 0.0 ~ 2.0, default: 0.2]
    S:movementSpeed=0.3

    # Configures the spawning frequency. Higher numbers mean more spawns. [range: 0 ~ 100, default: 4]
    I:weightProbability=22
}
 

running:
forge-14.23.2.2635 
java 1.8.0_161 64bit
ERZ version 1.3.7
biome: roofed forest

Sorry I'm unable to fix the formatting.

**Comment by Lothrazar** [comment]
Hey, thanks for being so patient, i havent paid enough attention to this mod. but i will be in future. 

Testing this in my own superflat worlds it seems fine.  Nothing spawns in the day, but they spawn all over at night.  Sevtech devs say they have no issues as well .
