### ISSUE TITLE
ERZ uses "roots" as its mod id?

### ISSUE THREAD

**Issue by Wabbit0101** [PrinceOfAmber/ERZ#27]
Is this intentional or should it be something distinct so other mods and distinguish betweeen the roots, .enderzoo, and erz

**Comment by Lothrazar** [comment]
No, i dont think so. "emberroot" is id.

https://github.com/PrinceOfAmber/ERZ/blob/master/src/main/java/teamroots/emberroot/Const.java#L3

and resources are all in 

https://github.com/PrinceOfAmber/ERZ/tree/master/src/main/resources/assets/emberroot

**Comment by Wabbit0101** [comment]
Bleech, thanks. Was looking at old roots2 github clone.
